apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: togglemaster
data:
  PORT: "8005"
  # Preencha com a URL da fila SQS e a região (obrigatório para o worker)
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/742792279914/togglemaster-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"


