apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: togglemaster
  labels:
    app.kubernetes.io/name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics
    spec:
      containers:
        - name: analytics
          image: 633853515534.dkr.ecr.us-east-1.amazonaws.com/togglemaster-analytics:v1.0.0-ffc41522b381e7b9d949fc445482f48122af930d
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
