apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster-analytics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kellfigueiredo/tech_challenge_3.git
    targetRevision: main
    path: gitops/apps/analytics
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
