name: CI — evaluation

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "services/evaluation/**"
      - ".github/workflows/ci-evaluation.yml"
      - ".github/workflows/reusable-go-microservice.yml"
      - ".golangci.yml"
      - "docker-compose.yml"
      - "Makefile"
  pull_request:
    paths:
      - "services/evaluation/**"
      - ".github/workflows/ci-evaluation.yml"
      - ".github/workflows/reusable-go-microservice.yml"
      - ".golangci.yml"
      - "docker-compose.yml"
      - "Makefile"

jobs:
  pipeline:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-go-microservice.yml
    secrets: inherit
    with:
      service_name: evaluation
      service_path: services/evaluation
      ecr_repository: togglemaster-evaluation
      gitops_manifest: gitops/apps/evaluation/deployment.yaml
