name: CI — flag

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
      - ".github/workflows/reusable-python-microservice.yml"
      - ".golangci.yml"
      - "docker-compose.yml"
      - "Makefile"
  pull_request:
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
      - ".github/workflows/reusable-python-microservice.yml"
      - ".golangci.yml"
      - "docker-compose.yml"
      - "Makefile"

jobs:
  pipeline:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-python-microservice.yml
    secrets: inherit
    with:
      service_name: flag
      service_path: services/flag
      ecr_repository: togglemaster-flag
      gitops_manifest: gitops/apps/flag/deployment.yaml
