name: CI — targeting

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "services/targeting/**"
      - ".github/workflows/ci-targeting.yml"
      - ".github/workflows/reusable-python-microservice.yml"
      - ".golangci.yml"
      - "docker-compose.yml"
      - "Makefile"
  pull_request:
    paths:
      - "services/targeting/**"
      - ".github/workflows/ci-targeting.yml"
      - ".github/workflows/reusable-python-microservice.yml"
      - ".golangci.yml"
      - "docker-compose.yml"
      - "Makefile"

jobs:
  pipeline:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-python-microservice.yml
    secrets: inherit
    with:
      service_name: targeting
      service_path: services/targeting
      ecr_repository: togglemaster-targeting
      gitops_manifest: gitops/apps/targeting/deployment.yaml
